source {C:/Xilinx92i/data/projnav/scripts/VsimStopServer.tcl}
-- Auto Generated by Project Navigator to simulate
-- HDL Bencher Annotated Test Bench
--
vlib work
onbreak {resume}
onerror {quit -code 99 -force}
onElabError {resume}
vcom -explicit  -93 "ctrl.vhd"
vcom -explicit  -93 "ROM32x24.vhd"
vcom -explicit  -93 "ProgCnt.vhd"
vcom -explicit  -93 "PC_Update.vhd"
vcom -explicit  -93 "MUX2V5.vhd"
vcom -explicit  -93 "MUX2V16.vhd"
vcom -explicit  -93 "File_Regs.vhd"
vcom -explicit  -93 "DataMem.vhd"
vcom -explicit  -93 "ALU.vhd"
vcom -explicit  -93 "PIC24.vhf"
vcom -explicit  -93 "testA.ant"
vsim -t 1ps   -lib work testA
run -all
quit -force
